### ISSUE TITLE
Using this docker with SyntaxNet

### ISSUE THREAD

**Issue by davidsbatista** [johndpope/DockerParseyAPI#7]
Is it possible to easily to adapt this docker to use SyntaxNet with other models/languages?

**Comment by johndpope** [comment]
I've raised this as an issue / the 'api' here under the hood is a grpc service
unfortunately - syntaxnet doesn't have a grpc layer.
https://github.com/tensorflow/tensorflow/issues/5061

the respective proto files are defined - albeit in proto2 format. 
@bogatyy - is it possible to use grpc with syntaxnet?

**Comment by davidsbatista** [comment]
I would like to use SyntaxNet trained for Portuguese, I'm still lost/confused with all the SyntaxNet/Tensorflow integration with Tensorflow serving. Do you have any suggestions on what to follow/read/explore?

Thanks nevertheless for your answer.

**Comment by wwe-johndpope** [comment]
It's a bit of rabbit hole. Docker is alluring because in a couple of lines of code you can potentially have a server up and running.


Take a look at the network /branches /forks on this project. I'm sure attempts have been beyond Korean.

https://github.com/dsindex/syntaxnet/blob/master/README_api.md

**Comment by johndpope** [comment]
try this instead
https://github.com/tensorflow/models/tree/7d30a017fe50b648be6dee544f8059bde52db562/syntaxnet

https://github.com/tensorflow/models/blob/7d30a017fe50b648be6dee544f8059bde52db562/syntaxnet/Dockerfile
